name: Deploy to S3
run-name: ${{ github.actor }} is deploying ${{ github.event_name }}
on:
    push:
        branches:
            - main # Set a branch to deploy
    pull_request:

jobs:
    deploy:
        runs-on: ubuntu-22.04
        permissions:
            id-token: write # Required for OIDC
            contents: read # Required to read files on the repository

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true # Fetch Hugo themes (true OR recursive)
                  fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v3
              with:
                  hugo-version: '0.119.0'
                  extended: true

            - name: Build
              run: hugo --minify

            - name: Setup AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  role-session-name: ${{ secrets.AWS_ROLE_SESSION_NAME }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Deploy to S3
              uses: jakejarvis/s3-sync-action@v0.5.1
              with:
                  args: --delete # Makes files public and removes old ones
              env:
                  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }} # Your S3 bucket name

            - name: Clear cloudfront cache
              run: |
                  set -e
                  aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CF_DIST_ID }} --paths "/*"
